# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 08:28
from __future__ import unicode_literals

import ddr.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', ddr.models.EmptyStringToNoneField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('[a-z0-9]*[a-z]+([a-z0-9]+)*([a-z0-9])*', 'Keys can only have lowercase letters and numbers. Keys must contain at least one letter.')])),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', ddr.models.EmptyStringToNoneField(max_length=100)),
                ('sort_name', models.CharField(max_length=100)),
                ('artist', ddr.models.EmptyStringToNoneField(max_length=100)),
                ('key', ddr.models.EmptyStringToNoneField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('[a-z0-9]*[a-z]+([a-z0-9]+)*([a-z0-9])*', 'Keys can only have lowercase letters and numbers. Keys must contain at least one letter.')])),
                ('us_locked', models.BooleanField(default=False)),
                ('floor_infection', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('challenge_has_shock_arrows', models.BooleanField(default=False)),
                ('single_beginner', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('single_beginner_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('single_basic', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('single_basic_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('single_difficult', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('single_difficult_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('single_expert', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('single_expert_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('single_challenge', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('single_challenge_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('double_basic', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('double_basic_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('double_difficult', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('double_difficult_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('double_expert', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('double_expert_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('double_challenge', ddr.models.EmptyStringToNoneField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19')], max_length=2, null=True)),
                ('double_challenge_video', ddr.models.EmptyStringToNoneField(blank=True, max_length=100, null=True)),
                ('folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddr.Folder')),
            ],
        ),
    ]
